### ISSUE TITLE
Release the last version

### ISSUE THREAD

**Issue by mazerte** [kuu/hls-parser#129]
Hi,

thanks for this awesome library. I want to use it for a new project I have but it seems that the last version published on NPM isn't that actual state of the lib.

In my project I need both Typescript and marker support. I found that @types/hls-parser project doesn't includes markers and if I use `npm install git@github.com:kuu/hls-parser.git` I get the right types for typescript but I can't compile anymore.

Let me know if I can help in any way.

Thanks

**Comment by kuu** [comment]
Hope this can be closed by the PR:
https://github.com/kuu/hls-parser/pull/134

Feel free to reopen if not.

**Comment by kuu** [comment]
Feel free to reopen.
