### ISSUE TITLE
Error when using `noImplicitAny` in a typescript project

### ISSUE THREAD

**Issue by brako** [kuu/hls-parser#136]
Hello,

I have multiple `noImplicitAny` errors when building my project, despites having the following config:

```json
{
    "skipLibCheck": true,
    "noImplicitAny": true
}
```

It is probably related to the issue:  https://github.com/microsoft/TypeScript/issues/15363

It looks like `.ts` file should not be shipped in the release.

Thanks

**Comment by ajfranzoia** [comment]
I'm having the same issue

**Comment by brako** [comment]
Looks like the .npmignore is configured to ignore .ts files but it is not working.
`*.ts
!*.d.ts`

Maybe the build output and sources should be in separate folders to prevent mixing them when publishing the module.

**Comment by indigolain** [comment]
It looks like the change to filter out the ts files in .npmignore was introduced on Oct 14, 2023.
https://github.com/kuu/hls-parser/commit/3d37ad8ef3a4836357e30764c8c43010cb8ed0a4

While the newest version of hls-parser was released Oct 9, 2023 according to npm, prior to the changes mentioned above.
https://www.npmjs.com/package/hls-parser?activeTab=versions

Maybe if we publish a new version, the problem will go away? @kuu is there any chance of deploying a new version?

**Comment by indigolain** [comment]
@kuu 
Thank you for responding so quickly!
Looks like `.ts` files are gone from the release as expected! ✨ I think we can close this issue 🚀

**Comment by kuu** [comment]
@indigolain Thanks for confirming that! Will close.
