### ISSUE TITLE
How to create a master playlist from media playlists?

### ISSUE THREAD

**Issue by murilozilli** [kuu/hls-parser#20]
I'm using ffmpeg to create media playlists. After that I wonder if there is a way to create a master playlist using this lib gluing all those media playlists varying them on bandwidth

**Comment by kuu** [comment]
It's possible to create a simple master playlist if you already have media playlists and segment files.
You can define EXT-X-STREAM-INF (Variant) by calculating bandwidth based on the duration and the byte size of the segment files.
Here's a pseudo code:
```js
const mediaPlayList = HLS.parse(fs.readFileSync('low.m3u8'));
const low = new Variant({uri: './low.m3u8', bandwidth: segmentsByteSizeLow * 8 / mediaPlayList.targetDuration}); // BANDWIDTH must be the peak bits/seconds though...
const mid = new Variant(....
const high = new Variant(....
const masterPlaylist = new MasterPlaylist({variants: [low, mid, high]});
return HLS.stringify(masterPlaylist);
```

**Comment by murilozilli** [comment]
Awesome. I had something like this in mind after looking at the tests altough I still have one question probably unralated to this tool so I am sorry if I am overstepping but do you know how to get this segment byte size from my segments? Should I use ffmpeg or something like this? 

To create the playlists and segments I am using the following code:

`ffmpeg -i 20170718_203132.mp4  -c 24 -vcodec libx264 -acodec aac -ac 1 -strict -2 -b:v 400k             -profile:v baseline -maxrate 400k -bufsize 1835k             -hls_time 10 -hls_playlist_type vod -vsync 1 -vf scale=-2:240             video_chunks/index0.m3u8`

**Comment by kuu** [comment]
I think you need to check every segment file size and duration to know the peak bitrate.
Here's an example of single-variant master playlist generation.

```js
const fs = require('fs');
const path = require('path');
const HLS = require('hls-parser');

const {MasterPlaylist, Variant} = HLS.types;
const BASE_DIR = path.join(__dirname, 'video_chunks');
const MEDIA_PLAYLIST = path.join(BASE_DIR, 'index0.m3u8');
const mediaPlaylistString = fs.readFileSync(MEDIA_PLAYLIST, {encoding: 'utf8'});
const {segments} = HLS.parse(mediaPlaylistString);

const maxBitrate = segments.reduce((max, segment) => {
  const SEGMENT = path.join(BASE_DIR, segment.uri);
  const {size} = fs.statSync(SEGMENT);
  const bitrate = size * 8 / segment.duration;
  return Math.max(max, bitrate);
}, 0);

const low = new Variant({uri: './index0.m3u8', bandwidth: Math.ceil(maxBitrate)});
const masterPlaylist = new MasterPlaylist({variants: [low]});

console.log(HLS.stringify(masterPlaylist));
```

**Comment by murilozilli** [comment]
I can't thank you enough man. This will be a huge help.

**Comment by Beloin** [comment]
This helped me too. Thanks a lot!
