### ISSUE TITLE
Can't add Redundant Streams to playlist variants 

### ISSUE THREAD

**Issue by meatherly** [kuu/hls-parser#22]
Just have to say great library so far! Been using it to generate playlist. 
I don't have a fix right off the top of my head after glancing at the code but I noticed that I can't add [Redundant Streams](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/UsingHTTPLiveStreaming/UsingHTTPLiveStreaming.html#//apple_ref/doc/uid/TP40008332-CH102-SW22) to the playlist variants when I call `HLS.stringify()`. My quick fix was to comment out https://github.com/kuu/hls-parser/blob/master/stringify.js#L18 but I'm pretty sure this would cause more problems then it would fix. 

Let me know if their is any way I can help.

Great work though, thanks!

**Comment by kuu** [comment]
Thanks for pointing out! I just didn't consider the use-case.
I've tried making the fix and already published it as v0.1.6
It would be nice if you could double-check.
Thanks

**Comment by meatherly** [comment]
Works! thanks for the speedy response!! Awesome library!!
