### ISSUE TITLE
CLOSED-CAPTIONS attribute doesn't honor spec

### ISSUE THREAD

**Issue by mdanilakis** [kuu/hls-parser#24]
Hi,

I've experienced the following issue during parse:
CLOSED-CAPTIONS attribute MUST match the value of the GROUP-ID attribute of an EXT-X-MEDIA tag 

The playlist has the following variant:
#EXT-X-STREAM-INF:BANDWIDTH=202000,AVERAGE-BANDWIDTH=184000,CODECS="mp4a.40.2,avc1.42C01E",RESOLUTION=192x108,FRAME-RATE=25,AUDIO="audio-aacl-64",CLOSED-CAPTIONS=NONE

But there's no closed caption group provided in the playlist.

However, I then checked the specification and found this:
The value can be either a quoted-string or an enumerated-string with the value NONE.

So it seems that the parse method does not honor that

**Comment by kuu** [comment]
Thanks for letting me know that.
Will check and get back to you!

**Comment by kuu** [comment]
@mdanilakis I believe the issue has been fixed by:
https://github.com/kuu/hls-parser/pull/26

I've already npm published the change as v0.1.8
Thanks

**Comment by mdanilakis** [comment]
Thanks for the quick fix @kuu, I'll try it asap.

**Comment by mdanilakis** [comment]
I've tested it and look great @kuu. Thanks.

**Comment by kuu** [comment]
Thanks for the confirmation. Will close the issue.
