### ISSUE TITLE
Use sample .m3u8 files from Apple's HLS example page

### ISSUE THREAD

**Issue by kuu** [kuu/hls-parser#33]
for testing:
https://developer.apple.com/streaming/examples/

**Comment by ost12666** [comment]
This throws an exception when parsing:

https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3

Error: Conditional Assert: Failed at [3]

**Comment by kuu** [comment]
The default behavior has changed and now the library does not throw unless {strictMode: true} is specified via HLS.setOptions()
The change has already been published as hls-parser@0.3.0

**Comment by ost12666** [comment]
Thanks, that works!
