### ISSUE TITLE
EXT-X-MAP Needs to be added to ALLOW_REDUNDANCY list in utils.js

### ISSUE THREAD

**Issue by indiestream** [kuu/hls-parser#34]
Per the revision 23 of the HLS spec, multiple EXT-X-MAP's can be contained in a media playlist as long as it comes after a DISCONTINUITY tag.

This effects fragmented mp4s or fmp4 when you are compositing different videos together. A new map file containing the videos PMT data needs to be inserted after the DISCONTINUITY flag.

As of right now hls-parser throws an error for Redundant Item which prevents these composited playlists from being loaded. 

'#EXT-X-MAP' needs to be added to the end of the ALLOW_REDUNDANCY constant in utils.js.

**Comment by kuu** [comment]
The [fix](https://github.com/kuu/hls-parser/pull/35) npm-published as v0.2.2
