### ISSUE TITLE
Handling ad markers SCTE-35

### ISSUE THREAD

**Issue by mohammad3008** [kuu/hls-parser#40]
Hi,
What about parsing and dealing with ad markers segments ?
i.e.

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:8
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:8.008,
1.ts
#EXT-X-CUE-OUT:15.000
#EXTINF:8.008,
2.ts
#EXTINF:8.008,
3.ts
#EXT-X-CUE-IN
#EXTINF:8.008,
4.ts
#EXT-X-ENDLIST

Thanks

**Comment by philhar88** [comment]
would also like the ability to parse EXT-X-CUE-OUT. This is used by all major DAI platforms (e.g. Google DAI)

**Comment by kuu** [comment]
EXT-X-CUE-OUT and  EXT-X-CUE-IN are now supported in v0.4.0
