### ISSUE TITLE
The library doesn't parse EXT-X-PART tag

### ISSUE THREAD

**Issue by sangk54** [kuu/hls-parser#61]
Below is an example

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:109791
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=3.12
#EXT-X-PART-INF:PART-TARGET=1.04
#EXTINF:3.96,
l_5797_63028341_109791.ts
#EXT-X-PART:DURATION=1,URI="l_5797_63032301_109792_0.ts"
#EXT-X-PART:DURATION=1,URI="l_5797_63032301_109792_1.ts"
#EXT-X-PART:DURATION=1,URI="l_5797_63032301_109792_2.ts"
#EXT-X-PART:DURATION=1.04,URI="l_5797_63032301_109792_3.ts"
#EXTINF:3.96,
l_5797_63032301_109792.ts
#EXT-X-PART:DURATION=1,URI="l_5797_63036261_109793_0.ts"
#EXT-X-PART:DURATION=1,URI="l_5797_63036261_109793_1.ts"
#EXT-X-PART:DURATION=1,URI="l_5797_63036261_109793_2.ts"
#EXT-X-PART:DURATION=1.04,URI="l_5797_63036261_109793_3.ts"

**Comment by kuu** [comment]
`EXT-X-PART` is now supported by https://github.com/kuu/hls-parser/pull/65
Also published to npm as v0.6.0
