### ISSUE TITLE
EXT-X-DATERANGE tags with no START-DATE attribute are not ignored with strictMode disabled

### ISSUE THREAD

**Issue by aaronleo28** [kuu/hls-parser#66]
https://github.com/kuu/hls-parser/blob/36988b90a5f75699eb1a2016116b8c31f63d6088/parse.js#L726

Might need an additional check for `dateRange.start` on this line for parsing EXT-X-DATERANGE tags with no START-DATE attribute.

Although this is a required field based on the RFC, I would expect these invalid tags to be skipped rather than throw an error if `strictMode` is disabled

The RFC is slightly ambiguous as it includes an example of the tag without this attribute https://tools.ietf.org/html/rfc8216#section-8.10

Currently we're seeing `TypeError: Cannot read property 'getTime' of undefined` errors for tags without START-DATE

**Comment by kuu** [comment]
@aaronleo28 Thanks for letting me know that.
I've just made a change to ignore the missing START-DATE and published the fix as hls-parser@0.6.1
