### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ajorg-aws** [kuu/hls-parser#76]
Hello. I see `"license": "MIT",` in [`package.json`](https://github.com/kuu/hls-parser/blob/master/package.json) but I can't find any actual license file in the project. The one condition in the MIT License is:

> The above copyright notice and this permission notice (including the next paragraph) shall be included in all copies or substantial portions of the Software.

But there are no copyright notices in the project, and the permission notice is not included in any portion of the software.

**Comment by kuu** [comment]
Thanks @ajorg-aws for pointing this out. I added a LICENSE file. https://github.com/kuu/hls-parser/pull/78
Do you think it's ok to just add the file to this repository and omit it from the npm package and the compiled JS file?
I just wanted to make those files light.

**Comment by ajorg-aws** [comment]
Just adding it to the repo does help a lot.
What we do to keep the npm package small is use something like this in a comment in the JavaScript:

```
/*! Copyright <your name>. SPDX-License-Identifier: MIT */
```

The `/*!` keeps it from being stripped out by webpack (unless you strip it out anyway) and the license identifier refers folks to https://spdx.org/licenses/MIT.html

**Comment by kuu** [comment]
Thanks for the tip. 👍  I added the line https://github.com/kuu/hls-parser/pull/79
I found that webpack generates a `.min.js.LICENSE.txt` file which is referred from `.min.js` file.
Seems like in that way I can write a longer statement.

**Comment by ajorg-aws** [comment]
Thanks!
