### ISSUE TITLE
support for EXT-X-PREFETCH

### ISSUE THREAD

**Issue by joeflateau** [kuu/hls-parser#84]
for the competing LHLS proposal, it would be helpful for hls-parser to be able to parse/serialize EXT-X-PREFETCH tags. 

https://github.com/video-dev/hlsjs-rfcs/blob/lhls-spec/proposals/0001-lhls.md

**Comment by kuu** [comment]
@joeflateau Thanks for the link.
Let me confirm if I understand you correctly.

- You're trying to suggest `EXT-X-PREFETCH` in hls.js
- `hls-parser` will be used to demo/test `EXT-X-PREFETCH` on the server side

Correct?

**Comment by joeflateau** [comment]
Yes, I'm trying to add low latency support for my streams using hls.js player. And I use hls-parser on the server to transform the playlists that ffmpeg creates to fit my needs. Unfortunately right now, that transformation results in the prefetch tags being dropped.

**Comment by joeflateau** [comment]
I just reread this and I think I misspoke. I am NOT the one proposing EXT-X-PREFETCH. It's already been proposed and is an open-source low latency HLS proposal that is parallel to apple's proposal. It is already built into the HLS.js player.

**Comment by kuu** [comment]
Thanks. I just merged your PR. https://github.com/kuu/hls-parser/pull/85

**Comment by joeflateau** [comment]
Thank you!
